export const RoutePath = {
  Login: "/login",
  VerifierSignup: "/sign-up/verifier",
  IssuerRequest: "/request-access/issuer",
  ForgotPassword: "/forgot-password",
  ResetPassword: "/reset-password",
  AdminLogin: "/admin/login",
  VerifierLogin: "/verifier/login",
  Activities: "/",
  Connections: "/connections",
  AdminUsers: "/admin/users",
  AdminRequests: "/admin/requests",
  ConnectionDetails: "/connections/:id",
  Templates: "/templates",
  TemplateCreate: "/templates/new",
  TemplateDetail: "/templates/:id",
  TemplateEdit: "/templates/:id/edit",
  Credentials: "/credentials",
  IssueCredential: "/credentials/issue",
  CredentialDetails: "/credentials/:id",
  Notifications: "/notifications",
  Settings: "/settings",
  RequestPresentation: "/request-presentation",
  RequestPresentationDetail: "/request-presentation/:id",
};
