#!/bin/sh

GOOGLE_CLIENT_ID_VALUE="${VITE_GOOGLE_CLIENT_ID:-$GOOGLE_CLIENT_ID}"

cat > envfile.js <<EOF
window.__RUNTIME_CONFIG__ = {
  SERVER_URL: "${VITE_SERVER_URL}",
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID_VALUE}",
};
EOF
